/*
 *
 * HomeDashboard constants
 *
 */

export const CHANGE_SALARY_VALUE_ACTION = 'app/HomeDashboard/CHANGE_SALARY_VALUE_ACTION';
export const CHANGE_REVENUE_GOAL_PERCENT_VALUE_ACTION = 'app/HomeDashboard/CHANGE_REVENUE_GOAL_PERCENT_VALUE_ACTION';
export const CHANGE_EBITDA_GOAL_PERCENT_VALUE_ACTION = 'app/HomeDashboard/CHANGE_EBITDA_GOAL_PERCENT_VALUE_ACTION';
export const SELECT_QUARTER_BONUS_MODE_ACTION = 'app/HomeDashboard/SELECT_QUARTER_BONUS_MODE_ACTION';
export const SELECT_YEAR_BONUS_MODE_ACTION = 'app/HomeDashboard/SELECT_YEAR_BONUS_MODE_ACTION';

export const QUARTER_BONUS = 'quarter';
export const YEAR_BONUS = 'year';
