/*
 *
 * HomeDashboard constants
 *
 */

export const CHANGE_SALARY_VALUE_ACTION = 'app/HomeDashboard/CHANGE_SALARY_VALUE_ACTION';
export const CHANGE_REVENUE_GOAL_PERCENT_VALUE_ACTION = 'app/HomeDashboard/CHANGE_REVENUE_GOAL_PERCENT_VALUE_ACTION';
export const CHANGE_EBITDA_GOAL_PERCENT_VALUE_ACTION = 'app/HomeDashboard/CHANGE_EBITDA_GOAL_PERCENT_VALUE_ACTION';
